### ISSUE TITLE
ImportError: cannot import name 'flx'

### ISSUE THREAD

**Issue by jakeh999** [flexxui/flexx#471]
Whenever running the master version of Flexx on Python 3.5 or 3.6, I get this error:

Traceback (most recent call last):
  File "flexx.py", line 7, in <module>
    from flexx import flx
  File "/home/pi/Documents/tests/flexx.py", line 7, in <module>
    from flexx import flx
ImportError: cannot import name 'flx'

Any suggestions?

**Comment by jakeh999** [comment]
Nevermind...I realized my file had the same name as the module, so Python was trying to import my script instead of the module

**Comment by almarklein** [comment]
Happens to the best of us :D

**Comment by zappfinger** [comment]
I have this same problem, struggling with it for hours now.
The strange thing is, flexx works fine in a Jupyter notebook, but not in a PyCharm project or a Python file..I have installed flexx via Anaconda but also via pip, so I have the required files in several locations now.

**Comment by zappfinger** [comment]
Thank you! That seems to work fine...

**Comment by zappfinger** [comment]
Most examples work goed, but the form example gives me:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/richard/anaconda/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Users/richard/anaconda/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/richard/py35env/lib/python3.5/site-packages/webruntime/_common.py", line 107, in <lambda>
    t = threading.Thread(target=lambda: time.sleep(4) or clean_dirs())
  File "/Users/richard/py35env/lib/python3.5/site-packages/webruntime/_manage.py", line 221, in clean_dirs
    pids = get_pid_list()
  File "/Users/richard/py35env/lib/python3.5/site-packages/webruntime/_manage.py", line 137, in get_pid_list
    out = subprocess.check_output(cmd).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 46623: invalid continuation byte

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Users/richard/anaconda/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Users/richard/anaconda/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/richard/py35env/lib/python3.5/site-packages/webruntime/_common.py", line 107, in <lambda>
    t = threading.Thread(target=lambda: time.sleep(4) or clean_dirs())
  File "/Users/richard/py35env/lib/python3.5/site-packages/webruntime/_manage.py", line 221, in clean_dirs
    pids = get_pid_list()
  File "/Users/richard/py35env/lib/python3.5/site-packages/webruntime/_manage.py", line 137, in get_pid_list
    out = subprocess.check_output(cmd).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 46375: invalid continuation byte

Traceback (most recent call last):
  File "/Users/richard/PycharmProjects/FlexxTest/flexxTest.py", line 49, in <module>
    m = flx.launch(ThemedForm, 'app')
  File "/Users/richard/py35env/lib/python3.5/site-packages/flexx/app/_funcs.py", line 231, in launch
    return a.launch(runtime, **runtime_kwargs)
  File "/Users/richard/py35env/lib/python3.5/site-packages/flexx/app/_app.py", line 166, in launch
    session._runtime = webruntime.launch(url, runtime=runtime, **runtime_kwargs)
  File "/Users/richard/py35env/lib/python3.5/site-packages/webruntime/__init__.py", line 200, in launch
    raise ValueError('Could not detect a suitable backend among %r.' % runtimes)
ValueError: Could not detect a suitable backend among ['firefox-app', 'nw-app'].

Process finished with exit code 1

**Comment by almarklein** [comment]
@zappfinger thanks for posting that. This looks like a problem with webruntime, I've created an issue there: https://github.com/flexxui/webruntime/issues/5
