### ISSUE TITLE
Getting errors on import

### ISSUE THREAD

**Issue by mathemagician314** [flexxui/flexx#473]
I'm trying to run an app using the most recent version of flexx from this repo and getting the following error:

Traceback (most recent call last):
  File "C:/Users/Shipping/Documents/Integration Dev/SquarespaceUploader/FlexxInventoryGui.py", line 12, in <module>
    from flexx import app, ui, event
  File "C:\Python37\lib\site-packages\flexx\ui\__init__.py", line 143, in <module>
    from ._widget import Widget, create_element
  File "C:\Python37\lib\site-packages\flexx\ui\_widget.py", line 44, in <module>
    class Widget(app.JsComponent):
  File "C:\Python37\lib\site-packages\flexx\event\_component.py", line 54, in __init__
    cls._init_hook2(name, bases, dct)
  File "C:\Python37\lib\site-packages\flexx\app\_component2.py", line 153, in _init_hook2
    cls.JS.CODE = cls._get_js()
  File "C:\Python37\lib\site-packages\flexx\app\_component2.py", line 248, in _get_js
    c = create_js_component_class(cls.JS, cls_name, base_class_name)
  File "C:\Python37\lib\site-packages\flexx\event\_js.py", line 543, in create_js_component_class
    code = mc.py2js(val, prototype_prefix + name)
  File "C:\Python37\lib\site-packages\flexx\event\_js.py", line 61, in py2js
    code = py2js(*args, **kwargs)
  File "C:\Python37\lib\site-packages\pscript\functions.py", line 145, in py2js
    return py2js_(ob)
  File "C:\Python37\lib\site-packages\pscript\functions.py", line 110, in py2js_
    p = Parser(pycode, (filename, linenr), **parser_options)
  File "C:\Python37\lib\site-packages\pscript\parser0.py", line 259, in __init__
    raise(err)
  File "C:\Python37\lib\site-packages\pscript\parser0.py", line 249, in __init__
    self._parts = self.parse(self._root)
  File "C:\Python37\lib\site-packages\pscript\parser0.py", line 435, in parse
    res = parse_func(node)
  File "C:\Python37\lib\site-packages\pscript\parser1.py", line 736, in parse_Module
    code += self.parse(child)
  File "C:\Python37\lib\site-packages\pscript\parser0.py", line 435, in parse
    res = parse_func(node)
  File "C:\Python37\lib\site-packages\pscript\parser2.py", line 974, in parse_FunctionDef
    code += self.parse(child)
  File "C:\Python37\lib\site-packages\pscript\parser0.py", line 435, in parse
    res = parse_func(node)
  File "C:\Python37\lib\site-packages\pscript\parser2.py", line 478, in parse_If
    code += self.parse(stmt)
  File "C:\Python37\lib\site-packages\pscript\parser0.py", line 435, in parse
    res = parse_func(node)
  File "C:\Python37\lib\site-packages\pscript\parser1.py", line 619, in parse_Assign
    code += self.parse(node.value_node)
  File "C:\Python37\lib\site-packages\pscript\parser0.py", line 435, in parse
    res = parse_func(node)
  File "C:\Python37\lib\site-packages\pscript\parser1.py", line 222, in parse_Dict
    raise JSError('Computed dict attributes are not supported on IE :/')
pscript.parser0.JSError: Error processing Dict-node in function "_create_pointer_event" in "C:\Python37\lib\site-packages\flexx\ui\_widget.py", line 939, col 18:
Computed dict attributes are not supported on IE :/

Since it's on import I'm pretty certain it's not my code, is a fix possible?

**Comment by mathemagician314** [comment]
Nevermind, different issue on update now

**Comment by almarklein** [comment]
I think the error is due to code that looks something like this:
```py
foo = 'mykey'
d = {mykey=3}
# or
d = {'my'+'key'=3}
```

However, this limitation has been removed recently, so it's probably a matter of updating flexx.

**Comment by almarklein** [comment]
Correction: update `pscript` (e.g. via `pip install pscript --upgrade`)
