### ISSUE TITLE
Can we use Python requests package within Flexx?

### ISSUE THREAD

**Issue by ericleman** [flexxui/flexx#487]
In my Flexx App, can I retrieve data from the web using a simple requests.get query, in order to update the UI?

I tried the code below:

```py
import requests
from flexx import app, ui, event

class Example(ui.Widget):
    def init(self):
        ui.Label(text='hello world')
        r = requests.get('https://flexx.readthedocs.io/en/latest/ui/intro.html',verify=False)

app.App(Example).launch('chromium-browser')
app.run()
```

This code generates an issue with pscript:
```
Traceback (most recent call last):
  File "testHTTPFlexx.py", line 22, in <module>
    class Example(ui.Widget):
  File "C:\Users\LEMANE\AppData\Local\Programs\Python\Python36\lib\site-packages\flexx\event\_component.py", line 54, in __init__
    cls._init_hook2(name, bases, dct)
  File "C:\Users\LEMANE\AppData\Local\Programs\Python\Python36\lib\site-packages\flexx\app\_component2.py", line 153, in _init_hook2
    cls.JS.CODE = cls._get_js()
  File "C:\Users\LEMANE\AppData\Local\Programs\Python\Python36\lib\site-packages\flexx\app\_component2.py", line 248, in _get_js
    c = create_js_component_class(cls.JS, cls_name, base_class_name)
  File "C:\Users\LEMANE\AppData\Local\Programs\Python\Python36\lib\site-packages\flexx\event\_js.py", line 543, in create_js_component_class
    code = mc.py2js(val, prototype_prefix + name)
  File "C:\Users\LEMANE\AppData\Local\Programs\Python\Python36\lib\site-packages\flexx\event\_js.py", line 61, in py2js
    code = py2js(*args, **kwargs)
  File "C:\Users\LEMANE\AppData\Local\Programs\Python\Python36\lib\site-packages\pscript\functions.py", line 145, in py2js
    return py2js_(ob)
  File "C:\Users\LEMANE\AppData\Local\Programs\Python\Python36\lib\site-packages\pscript\functions.py", line 110, in py2js_
    p = Parser(pycode, (filename, linenr), **parser_options)
  File "C:\Users\LEMANE\AppData\Local\Programs\Python\Python36\lib\site-packages\pscript\parser0.py", line 259, in __init__
    raise(err)
  File "C:\Users\LEMANE\AppData\Local\Programs\Python\Python36\lib\site-packages\pscript\parser0.py", line 249, in __init__
    self._parts = self.parse(self._root)
  File "C:\Users\LEMANE\AppData\Local\Programs\Python\Python36\lib\site-packages\pscript\parser0.py", line 435, in parse
    res = parse_func(node)
  File "C:\Users\LEMANE\AppData\Local\Programs\Python\Python36\lib\site-packages\pscript\parser1.py", line 829, in parse_Module
    code += self.parse(child)
  File "C:\Users\LEMANE\AppData\Local\Programs\Python\Python36\lib\site-packages\pscript\parser0.py", line 435, in parse
    res = parse_func(node)
  File "C:\Users\LEMANE\AppData\Local\Programs\Python\Python36\lib\site-packages\pscript\parser2.py", line 988, in parse_FunctionDef
    code += self.parse(child)
  File "C:\Users\LEMANE\AppData\Local\Programs\Python\Python36\lib\site-packages\pscript\parser0.py", line 435, in parse
    res = parse_func(node)
  File "C:\Users\LEMANE\AppData\Local\Programs\Python\Python36\lib\site-packages\pscript\parser1.py", line 712, in parse_Assign
    code += self.parse(node.value_node)
  File "C:\Users\LEMANE\AppData\Local\Programs\Python\Python36\lib\site-packages\pscript\parser0.py", line 435, in parse
    res = parse_func(node)
  File "C:\Users\LEMANE\AppData\Local\Programs\Python\Python36\lib\site-packages\pscript\parser1.py", line 503, in parse_Call
    res = self._methods[method_name](node, base_name)
  File "C:\Users\LEMANE\AppData\Local\Programs\Python\Python36\lib\site-packages\pscript\parser3.py", line 442, in method_X
    raise JSError('Method %s does not support keyword args.' % name)
pscript.parser0.JSError: Error processing Call-node in function "init" in "testHTTPFlexx.py", line 26, col 8:
Method get does not support keyword args.
```

**Comment by ericleman** [comment]
Sorry, I missed the formatting of my code. Here it is:
```import requests
from flexx import app, ui, event

class Example(ui.Widget):
    def init(self):
        ui.Label(text='hello world')
        r = requests.get('https://flexx.readthedocs.io/en/latest/ui/intro.html',verify=False)

app.App(Example).launch('chromium-browser')
app.run()```

**Comment by almarklein** [comment]
(you can use ` ```py ... ``` ` to format with Python syntax)

Your `Example` widget is a widget, thus a `JsComponent`. It runs in JS so you cannot use the request library there. You can use JavaScript fetch though:

```py
from flexx import app, ui, event

class Example(ui.Widget):
    def init(self):
        ui.Label(text='hello world')
        self.init2()  # invoke the async init
   
    async def init2(self):  # this func must be async to be able to use await
        r = await window.fetch(('https://flexx.readthedocs.io/en/latest/ui/intro.html', dict(method='GET'))
        ...

app.App(Example).launch('chromium-browser')
app.run()
```
