### ISSUE TITLE
Example from docs not working

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#568]
Hi,

On page https://flexx.readthedocs.io/en/stable/guide/event_system.html of the documentation, there is an example of setting a label's text using a function:
```python
flx.Label(flex=1, text=lambda: 'count is ' + str(self.counter))
```
When using this in an application it throws:
```
Uncaught exception GET /flexx/ws/MyFlexxApp(::1)
HTTPServerRequest(protocol='http', host='localhost:49192', method='GET', uri='/flexx/ws/ScanergoWebApp', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\tornado-6.0a1-py3.7-win-amd64.egg\tornado\websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "C:\Python37\lib\site-packages\flexx-0.7.1-py3.7.egg\flexx\app\_tornadoserver.py", line 543, in on_message
    cookies=self.cookies)
  File "C:\Python37\lib\site-packages\flexx-0.7.1-py3.7.egg\flexx\app\_app.py", line 516, in connect_client
    session._set_ws(ws)
  File "C:\Python37\lib\site-packages\flexx-0.7.1-py3.7.egg\flexx\app\_session.py", line 225, in _set_ws
    self._ws.write_command(command)
  File "C:\Python37\lib\site-packages\flexx-0.7.1-py3.7.egg\flexx\app\_tornadoserver.py", line 609, in write_command
    bb = serializer.encode(cmd)
  File "C:\Python37\lib\site-packages\flexx-0.7.1-py3.7.egg\flexx\app\bsdf_lite.py", line 397, in encode
    self.save(f, ob)
  File "C:\Python37\lib\site-packages\flexx-0.7.1-py3.7.egg\flexx\app\bsdf_lite.py", line 407, in save
    self._encode(f, ob, None)
  File "C:\Python37\lib\site-packages\flexx-0.7.1-py3.7.egg\flexx\app\bsdf_lite.py", line 193, in _encode
    self._encode(f, v, None)
  File "C:\Python37\lib\site-packages\flexx-0.7.1-py3.7.egg\flexx\app\bsdf_lite.py", line 201, in _encode
    self._encode(f, v, None)
  File "C:\Python37\lib\site-packages\flexx-0.7.1-py3.7.egg\flexx\app\bsdf_lite.py", line 283, in _encode
    raise TypeError(t % value.__class__.__name__)
TypeError: Class 'function' is not a valid base BSDF type, nor is it handled by an extension.
```

I'm on Windows 10, Python 3.7, Flexx 0.7.1

**Comment by almarklein** [comment]
Yeah, this can be a bit confusing. Setting a property to a lambda like that does not work "over the websocket". So it will work when you do it for a property of a PyComponent, or if you do it in the `init()` of a `JSComponent`. But it will not work if you do it in the `init()` of a PyComponent when the property' sobject is a `JSComponent`.

**Comment by matkuki** [comment]
Thanks for the explanation.
