### ISSUE TITLE
RuntimeError: Cannot convert Constant nodes.

### ISSUE THREAD

**Issue by LewisNeal** [flexxui/flexx#608]
With python 3.8 installed, running the sine.py example, the script fails with the following error:

Traceback (most recent call last):
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\pscript\commonast.py", line 808, in _convert
    converter = getattr(self, '_convert_' + type)
AttributeError: 'NativeAstConverter' object has no attribute '_convert_Constant'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sine.py", line 6, in <module>
    from flexx import flx
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\flexx\flx.py", line 10, in <module>
    from .app import *
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\flexx\app\__init__.py", line 38, in <module>
    from ._app import App, manager
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\flexx\app\_app.py", line 17, in <module>
    from ._component2 import PyComponent, JsComponent
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\flexx\app\_component2.py", line 19, in <module>
    from ..event._js import create_js_component_class
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\flexx\event\_js.py", line 598, in <module>
    JS_FUNCS = (mc.py2js(_mutate_array_js) + '\nvar mutate_array = _mutate_array_js;\n' +
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\flexx\event\_js.py", line 61, in py2js
    code = py2js(*args, **kwargs)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\pscript\functions.py", line 145, in py2js
    return py2js_(ob)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\pscript\functions.py", line 110, in py2js_
    p = Parser(pycode, (filename, linenr), **parser_options)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\pscript\parser0.py", line 214, in __init__
    self._root = ast.parse(code)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\pscript\commonast.py", line 39, in parse
    return converter.convert(comments)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\pscript\commonast.py", line 791, in convert
    node = self._convert(native_node)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\pscript\commonast.py", line 812, in _convert
    val = converter(n)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\pscript\commonast.py", line 927, in _convert_Expr
    return Expr(self._convert(n.value))
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\pscript\commonast.py", line 810, in _convert
    raise RuntimeError('Cannot convert %s nodes.' % type)
RuntimeError: Cannot convert Constant nodes.

**Comment by LewisNeal** [comment]
Just noticed that this is due to py3.8 not being supported yet, and relates to https://github.com/flexxui/pscript/pull/32

**Comment by icarito** [comment]
Just a note that as 3.8 becomes default more people will be affected (just hit this with Archlinux). Thanks for pscript it's nice!

**Comment by icarito** [comment]
the patch in https://github.com/flexxui/pscript/pull/32 works for me (just drop it in the installed pscript location as a workaround).

**Comment by almarklein** [comment]
Updating Pscript to 0.7.3 should fix this issue.
