### ISSUE TITLE
problem using json library

### ISSUE THREAD

**Issue by liviolima80** [flexxui/flexx#609]
I have a problem using the following simple code:

```py
from flexx import flx
import json

def get_list():
    x =  '{ "name":"John", "age":30, "city":"New York"}'
    data = json.loads(x)
    tools = list(data.keys())
    return tools

class ToolsTree(flx.Widget):
    def init(self):
        tools = get_list()
        with flx.TreeWidget(flex=0, max_selected=1) as self.tree:
            for t in tools:
                flx.TreeItem(text=t, checked=None)
                                                              
if __name__ == '__main__':
    app = flx.App(ToolsTree)
    assets = app.export('index.html', link=0)
```

I get the following error:
```
[I 11:48:14 flexx.app] Asset store collected 2 new modules.
Traceback (most recent call last):
  File "tools_simple.py", line 31, in <module>
    assets = app.export('index.html', link=0)
  File "C:\anaconda3\envs\web_dev\lib\site-packages\flexx\app\_app.py", line 291, in export
    d = self.dump(fname, link)
  File "C:\anaconda3\envs\web_dev\lib\site-packages\flexx\app\_app.py", line 221, in dump
    self(flx_session=session, flx_is_app=True)
  File "C:\anaconda3\envs\web_dev\lib\site-packages\flexx\app\_app.py", line 77, in __call__
    return self.cls(*a, **kw)
  File "C:\anaconda3\envs\web_dev\lib\site-packages\flexx\app\_component2.py", line 458, in __init__
    super().__init__(**kwargs)
  File "C:\anaconda3\envs\web_dev\lib\site-packages\flexx\event\_component.py", line 209, in __init__
    self._comp_init_property_values(property_values)
  File "C:\anaconda3\envs\web_dev\lib\site-packages\flexx\app\_component2.py", line 463, in _comp_init_property_values
    local_inst = self._comp_init_app_component(property_values)  # pops items
  File "C:\anaconda3\envs\web_dev\lib\site-packages\flexx\app\_component2.py", line 340, in _comp_init_app_component
    self._session._register_component(self, custom_id)
  File "C:\anaconda3\envs\web_dev\lib\site-packages\flexx\app\_session.py", line 392, in _register_component
    self._register_component_class(cls)
  File "C:\anaconda3\envs\web_dev\lib\site-packages\flexx\app\_session.py", line 444, in _register_component_class
    self._register_module(cls.__jsmodule__)
  File "C:\anaconda3\envs\web_dev\lib\site-packages\flexx\app\_session.py", line 473, in _register_module
    self._store.update_modules()  # Ensure up-to-date module definition
  File "C:\anaconda3\envs\web_dev\lib\site-packages\flexx\app\_assetstore.py", line 282, in update_modules
    self._modules[cls.__jsmodule__].add_variable(cls.__name__)
  File "C:\anaconda3\envs\web_dev\lib\site-packages\flexx\app\_modules.py", line 318, in add_variable
    self._collect_dependencies(val.JS.CODE, _dep_stack)
  File "C:\anaconda3\envs\web_dev\lib\site-packages\flexx\app\_modules.py", line 422, in _collect_dependencies
    self.add_variable(name, _dep_stack=_dep_stack)
  File "C:\anaconda3\envs\web_dev\lib\site-packages\flexx\app\_modules.py", line 370, in add_variable
    self._collect_dependencies(js, _dep_stack)
  File "C:\anaconda3\envs\web_dev\lib\site-packages\flexx\app\_modules.py", line 422, in _collect_dependencies
    self.add_variable(name, _dep_stack=_dep_stack)
  File "C:\anaconda3\envs\web_dev\lib\site-packages\flexx\app\_modules.py", line 375, in add_variable
    self._import(mod_name, val.__name__, name)
  File "C:\anaconda3\envs\web_dev\lib\site-packages\flexx\app\_modules.py", line 218, in _import
    m.add_variable(name)
  File "C:\anaconda3\envs\web_dev\lib\site-packages\flexx\app\_modules.py", line 370, in add_variable
    self._collect_dependencies(js, _dep_stack)
  File "C:\anaconda3\envs\web_dev\lib\site-packages\flexx\app\_modules.py", line 422, in _collect_dependencies
    self.add_variable(name, _dep_stack=_dep_stack)
  File "C:\anaconda3\envs\web_dev\lib\site-packages\flexx\app\_modules.py", line 370, in add_variable
    self._collect_dependencies(js, _dep_stack)
  File "C:\anaconda3\envs\web_dev\lib\site-packages\flexx\app\_modules.py", line 422, in _collect_dependencies
    self.add_variable(name, _dep_stack=_dep_stack)
  File "C:\anaconda3\envs\web_dev\lib\site-packages\flexx\app\_modules.py", line 408, in add_variable
    raise ValueError(t % (self.filename, name, val.__class__))
ValueError: JS in "C:\anaconda3\envs\web_dev\lib\json\__init__.py" uses 'codecs.BOM_UTF8' but cannot convert <class 'bytes'> to JS.
```

**Comment by almarklein** [comment]
That code runs in JS, so you cannot use Python JSON module there. You want to use JS's own JSON parser (`JSON.stringify()` and `JSON.parse()`).
