### ISSUE TITLE
How do I plot 3D meshing using plotly in flexx?

### ISSUE THREAD

**Issue by shijianjian** [flexxui/flexx#610]
I took an example from Plotly for 3D ploting but getting an error with:
```
Traceback (most recent call last):
  File "flexx_plotly.py", line 22, in <module>
    flx.launch(PlotlyGeoDemo)
  File "/home/ovs-dl/anaconda3/envs/dl/lib/python3.6/site-packages/flexx/app/_funcs.py", line 231, in launch
    return a.launch(runtime, **runtime_kwargs)
  File "/home/ovs-dl/anaconda3/envs/dl/lib/python3.6/site-packages/flexx/app/_app.py", line 157, in launch
    session = manager.create_session(self.name)
  File "/home/ovs-dl/anaconda3/envs/dl/lib/python3.6/site-packages/flexx/app/_app.py", line 580, in create_session
    app(flx_session=session, flx_is_app=True)
  File "/home/ovs-dl/anaconda3/envs/dl/lib/python3.6/site-packages/flexx/app/_app.py", line 77, in __call__
    return self.cls(*a, **kw)
  File "/home/ovs-dl/anaconda3/envs/dl/lib/python3.6/site-packages/flexx/app/_component2.py", line 458, in __init__
    super().__init__(**kwargs)
  File "/home/ovs-dl/anaconda3/envs/dl/lib/python3.6/site-packages/flexx/event/_component.py", line 209, in __init__
    self._comp_init_property_values(property_values)
  File "/home/ovs-dl/anaconda3/envs/dl/lib/python3.6/site-packages/flexx/app/_component2.py", line 463, in _comp_init_property_values
    local_inst = self._comp_init_app_component(property_values)  # pops items
  File "/home/ovs-dl/anaconda3/envs/dl/lib/python3.6/site-packages/flexx/app/_component2.py", line 340, in _comp_init_app_component
    self._session._register_component(self, custom_id)
  File "/home/ovs-dl/anaconda3/envs/dl/lib/python3.6/site-packages/flexx/app/_session.py", line 392, in _register_component
    self._register_component_class(cls)
  File "/home/ovs-dl/anaconda3/envs/dl/lib/python3.6/site-packages/flexx/app/_session.py", line 444, in _register_component_class
    self._register_module(cls.__jsmodule__)
  File "/home/ovs-dl/anaconda3/envs/dl/lib/python3.6/site-packages/flexx/app/_session.py", line 473, in _register_module
    self._store.update_modules()  # Ensure up-to-date module definition
  File "/home/ovs-dl/anaconda3/envs/dl/lib/python3.6/site-packages/flexx/app/_assetstore.py", line 282, in update_modules
    self._modules[cls.__jsmodule__].add_variable(cls.__name__)
  File "/home/ovs-dl/anaconda3/envs/dl/lib/python3.6/site-packages/flexx/app/_modules.py", line 318, in add_variable
    self._collect_dependencies(val.JS.CODE, _dep_stack)
  File "/home/ovs-dl/anaconda3/envs/dl/lib/python3.6/site-packages/flexx/app/_modules.py", line 422, in _collect_dependencies
    self.add_variable(name, _dep_stack=_dep_stack)
  File "/home/ovs-dl/anaconda3/envs/dl/lib/python3.6/site-packages/flexx/app/_modules.py", line 408, in add_variable
    raise ValueError(t % (self.filename, name, val.__class__))
ValueError: JS in "flexx_plotly.py" uses 'data' but cannot convert <class 'plotly.graph_objs.Mesh3d'> to JS.
```
Code:
```python

from flexx import flx
import plotly.graph_objects as go
import numpy as np

pts = np.loadtxt(np.DataSource().open('https://raw.githubusercontent.com/plotly/datasets/master/mesh_dataset.txt'))
x, y, z = pts.T

data = go.Mesh3d(x=x, y=y, z=z, color='lightpink', opacity=0.50)


class PlotlyGeoDemo(flx.HBox):

    def init(self):
        flx.PlotlyWidget(data=data)


if __name__ == '__main__':
    flx.launch(PlotlyGeoDemo)
    flx.run()

```

**Comment by almarklein** [comment]
I can see the same error when I run that. 

The docs of `flx.PlotlyWidget.data`: The data (list of dicts) that describes the plot. This can e.g. be the output of the Python plotly API call.

It looks like the output of `go.Mesh3d` is a special kind of Plotly object. My first take was to do `data = [data.to_plotly_json()]`, but despite the name, the resulting dict is not JSON compatible. The bottom line is that the viz representation must be something that Flexx can serialize. Flexx does support numpy arrays, but not Plotly's own specific stuff.

I don't know much about Plotly myself. Maybe they changed how it works, or maybe you're using a higher level API?

**Comment by ikaradogan** [comment]
You can use plotly's own json encoder to use plotly figure object. flx.PlotlyWidget does not directly use the figure object (at least for now), so you should load encoded json values to (data, layout) tuple. Then send _data_ and _layout_ to PlotlyWidget.

This code works:

``` python
import json

import numpy as np
import plotly.graph_objects as go
from flexx import flx

pts = np.loadtxt(np.DataSource().open('https://raw.githubusercontent.com/plotly/datasets/master/mesh_dataset.txt'))
x, y, z = pts.T

mesh = go.Mesh3d(x=x, y=y, z=z, color='lightpink', opacity=0.50)
fig = go.Figure(data=[mesh])

#  here, inside json.loads() you can use fig.to_json()
#  or json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)
data, layout = json.loads(fig.to_json()).values()


class PlotlyGeoDemo(flx.HBox):

    def init(self):
        flx.PlotlyWidget(data=data, layout=layout)


if __name__ == '__main__':
    flx.launch(PlotlyGeoDemo)
    flx.run()
```
