### ISSUE TITLE
Error running the simple plotly example

### ISSUE THREAD

**Issue by TristanKnox** [flexxui/flexx#618]
I have been trying to get a PlotlyWidget to show a plot but have been getting an error. I decided to try using the simple example given on the docs page a try just to make sure it was something I was doing on my end. But when running the example I get the same error.

Code:
![Capture](https://user-images.githubusercontent.com/43253719/72471723-38ce3a80-37b1-11ea-9c4e-a05ea0d7aad3.PNG)

Traceback:
![T1](https://user-images.githubusercontent.com/43253719/72472501-acbd1280-37b2-11ea-893a-3c8c835f979e.PNG)
![T2](https://user-images.githubusercontent.com/43253719/72472503-ae86d600-37b2-11ea-963d-87550f9617fe.PNG)

This error does not occur if I remove the line with flx.PlotlyWidget(data)

**Comment by TristanKnox** [comment]
I just figured out what the markdown syntax is so this is the same as the original post but with inline code if its helpful.
```python
from flexx import flx

class Example(flx.PlotWidget):
    def init(self):
        data = [{'type': 'bar',
                'x': ['giraffes', 'orangutans', 'monkeys'],
                'y': [20, 14, 23]}]

        with flx.Layout():
            flx.PlotlyWidget(data)


if __name__ == '__main__':
    flx.launch(Example)
    flx.run()
```

Traceback
```
Traceback (most recent call last):
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1319, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 966, in send
    self.connect()
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1422, in connect
    server_hostname=server_hostname)
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/knoxt/Projects/burner-scale-model/src/flexx/ui/pyplot_test.py", line 75, in <module>
    flx.launch(Example)
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\site-packages\flexx\app\_funcs.py", line 231, in launch
    return a.launch(runtime, **runtime_kwargs)
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\site-packages\flexx\app\_app.py", line 157, in launch
    session = manager.create_session(self.name)
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\site-packages\flexx\app\_app.py", line 580, in create_session
    app(flx_session=session, flx_is_app=True)
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\site-packages\flexx\app\_app.py", line 77, in __call__
    return self.cls(*a, **kw)
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\site-packages\flexx\app\_component2.py", line 458, in __init__
    super().__init__(**kwargs)
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\site-packages\flexx\event\_component.py", line 209, in __init__
    self._comp_init_property_values(property_values)
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\site-packages\flexx\app\_component2.py", line 463, in _comp_init_property_values
    local_inst = self._comp_init_app_component(property_values)  # pops items
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\site-packages\flexx\app\_component2.py", line 340, in _comp_init_app_component
    self._session._register_component(self, custom_id)
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\site-packages\flexx\app\_session.py", line 392, in _register_component
    self._register_component_class(cls)
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\site-packages\flexx\app\_session.py", line 444, in _register_component_class
    self._register_module(cls.__jsmodule__)
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\site-packages\flexx\app\_session.py", line 516, in _register_module
    self.send_command('DEFINE', suffix, asset.name, asset.to_string())
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\site-packages\flexx\app\_asset.py", line 195, in to_string
    self._source_str = self._get_from_url(self._source)
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\site-packages\flexx\app\_asset.py", line 203, in _get_from_url
    return urlopen(req, timeout=5.0).read().decode()
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1362, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Users\knoxt\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1321, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>

Process finished with exit code 1

```

**Comment by almarklein** [comment]
The plotlywidget tries to access 'https://cdn.plot.ly/plotly-latest.min.js'. Could it be that a firewall is blocking it?

**Comment by almarklein** [comment]
The example does not work btw. This would be the corresponding standalone example:
```py
from flexx import flx

class Example(flx.Widget):
    def init(self):
        data = [{'type': 'bar',
                'x': ['giraffes', 'orangutans', 'monkeys'],
                'y': [20, 14, 23]}]

        with flx.HBox():
            flx.PlotlyWidget(data=data)


if __name__ == '__main__':
    flx.launch(Example)
    flx.run()
```

**Comment by TristanKnox** [comment]
Thanks for getting back to me. I still get the same error after fixing the data=data that you pointed out I was missing. Perhaps it is a firewall issue. I will look into that and report back if I get it figured out.

**Comment by TristanKnox** [comment]
Can the Flexx PlotlyWidget run offline? I know that when using plotly you can specify that you want to run offline and am hoping that there is a way to set the PlotlyWidget to utilize that.

**Comment by almarklein** [comment]
I think what you'd have to do in that case is copy the code in `flexx/ui/widgets/_plotly.py`, download the `plotly.js` to your project, and change the `associate_asset` call to eomething like this:
```py
plotlyjs_source = open("path/to/plotly-latest.min.js").read()
app.assets.associate_asset(__name__, 'plotly-latest.min.js', plotlyjs_source)
```

**Comment by TristanKnox** [comment]
That worked, thanks.

**Comment by TristanKnox** [comment]
I couldn't locate any file called 'plotly-latest.min.js' but did find 'plotly.min.js' and using that worked just fine.
