### ISSUE TITLE
Need to change event loop policy to make Tornado work with asyncio on Python 3.8 Windows

### ISSUE THREAD

**Issue by LewisNeal** [flexxui/flexx#619]
Running the hello_world.py example I get this traceback:

[I 08:01:06 flexx.app] Asset store collected 2 new modules.
Traceback (most recent call last):
  File "Flexx_hello_world.py", line 22, in <module>
    m = flx.launch(Main)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\flexx\app\_funcs.py", line 231, in launch
    return a.launch(runtime, **runtime_kwargs)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\flexx\app\_app.py", line 152, in launch
    current_server()
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\flexx\app\_server.py", line 78, in current_server
    create_server()
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\flexx\app\_server.py", line 59, in create_server
    _current_server = TornadoServer(host, port, loop, **server_kwargs)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\flexx\app\_tornadoserver.py", line 56, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\flexx\app\_server.py", line 118, in __init__
    self._open(host, port, **kwargs)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\flexx\app\_tornadoserver.py", line 117, in _open
    self._server.listen(port, host)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\site-packages\tornado\platform\asyncio.py", line 99, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
[end]

System info:
Windows 10 AMD64 (build 10.0.18362) SP0
Python 3.8.1
Flexx       0.8.0
dialite         0.5.2
PScript         0.7.3
tornado         6.0.3
webruntime       0.5.6

Regards
Lewis

**Comment by almarklein** [comment]
It looks like Tornado is calling `asyncio.add_reader()`, which for some reason raises NotImplementedError.

It looks like it's a [known issue](https://github.com/tornadoweb/tornado/issues/2608) and also documented [here](https://github.com/tornadoweb/tornado/blob/18b653cf93fe870cbc630fb48595e1b92fc1e06c/tornado/platform/asyncio.py#L15).

The current solution.workaround seems to be to add this to yout code:
```py
if sys.platform == 'win32':
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```

There are a lot of project that are running into this. Let's wait a bit and see if the Tornado project is able to fix this.

**Comment by StanleyL4** [comment]
> It looks like Tornado is calling `asyncio.add_reader()`, which for some reason raises NotImplementedError.
> 
> It looks like it's a [known issue](https://github.com/tornadoweb/tornado/issues/2608) and also documented [here](https://github.com/tornadoweb/tornado/blob/18b653cf93fe870cbc630fb48595e1b92fc1e06c/tornado/platform/asyncio.py#L15).
> 
> The current solution.workaround seems to be to add this to yout code:
> 
> ```python
> if sys.platform == 'win32':
>     asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
> ```
> 
> There are a lot of project that are running into this. Let's wait a bit and see if the Tornado project is able to fix this.

I added this command on  `flexx>app>_tornadoserver.py` and it worked

**Comment by mkohli** [comment]
Hi ,
I started exploring Flexx today and I encountered NotImplemented Error. I am working on the basic widget code:
from flexx import flx

class Example(flx.Widget):

    def init(self):
        flx.Button(text='hello')
        flx.Button(text='world')

app = flx.App(Example)
app.export('example.html', link=0)  # Export to single file
app.launch('browser')
flx.run()

As suggested by you I added if sys.platform == 'win32':
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy()) to
flexx>app>_tornadoserver.py.
Now when I run the code I am getting RuntimeError as shown below:
[I 23:43:43 flexx.app] Asset store collected 2 new modules.
[I 23:43:44 flexx.app] Asset store collected 25 new modules.
[I 23:43:44 flexx.app] Exported standalone app to 'F:\\2020\\GUI\\Flex\\code\\example.html'
[I 23:43:44 flexx.app] Serving apps at http://localhost:49190/
Traceback (most recent call last):
  File "F:\2020\GUI\Flex\code\widget.py", line 12, in <module>
    flx.run()
  File "C:\Users\MYPC\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flexx\app\_funcs.py", line 44, in run
    return start()
  File "C:\Users\MYPC\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flexx\app\_funcs.py", line 34, in start
    server.start()
  File "C:\Users\MYPC\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flexx\app\_server.py", line 143, in start
    raise RuntimeError('Can only start server in same thread that created it.')
RuntimeError: Can only start server in same thread that created it.

Please help
Thank you

**Comment by mkohli** [comment]
I also have python 3.7.6 and I installed Flexx again for it and the code worked perfectly fine. So, till I get a response from you I will continue using Flexx with python 3.7.6

**Comment by metaperl** [comment]
This bug means that the [basic intro](https://flexx.readthedocs.io/en/stable/guide/widget_basics.html#turning-a-widget-into-an-app) doesnt even work completely. This has been a problem for 3 months now.

**Comment by almarklein** [comment]
The workaround:
```py
import sys, asyncio

if sys.version_info > (3, 8) and sys.platform.startswith('win'):
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```

Now to determine whether we should document that users should apply this, or whether we can add these lines in Flexx somewhere. Will have a better look on Monday.

**Comment by almarklein** [comment]
Done. Will also do a release shortly.
