### ISSUE TITLE
Embedding javascript interactive animation

### ISSUE THREAD

**Issue by avivazran** [flexxui/flexx#642]
Is there a way to create an animated widget such as the one here
[https://codepen.io/Staak/pen/XowdeE](url)  
if so, could you add an example or an explanation for how to do it?

what iv'e tried:
```python
app.assets.associate_asset(__name__,"js/jquery.flightindicators.js")  
app.assets.associate_asset(__name__,"css/flightindicators.css")
```

fails with

```python
Traceback (most recent call last):
  File "D:/CodeProjects/WebAppsPlayground/main.py", line 13, in <module>
    app.assets.associate_asset(__name__,"js/jquery.flightindicators.js")
  File "C:\Users\avivz\anaconda3\envs\drone_simulator\lib\site-packages\flexx\app\_assetstore.py", line 400, in associate_asset
    asset = Asset(asset_name, source)
  File "C:\Users\avivz\anaconda3\envs\drone_simulator\lib\site-packages\flexx\app\_asset.py", line 111, in __init__
    raise TypeError('Asset needs a source.')
TypeError: Asset needs a source.
```

thank you

**Comment by almarklein** [comment]
You need to supply a source:
`app.assets.associate_asset(__name__,"js/jquery.flightindicators.js", source)`

where source can be the source code, an url to the source code, or a function that returns the source code.
